// Generated by https://quicktype.io

export interface RandomResult {
  id: string;
  slug: string;
  alternative_slugs: AlternativeSlugs;
  created_at: string;
  updated_at: string;
  promoted_at: string;
  width: number;
  height: number;
  color: string;
  blur_hash: string;
  description: null | string;
  alt_description: string;
  breadcrumbs: [];
  urls: Urls;
  links: RandomResultLinks;
  likes: number;
  liked_by_user: boolean;
  current_user_collections: [];
  sponsorship: null;
  topic_submissions: TopicSubmissions;
  asset_type: AssetType;
  user: User;
  exif: Exif;
  location: Location;
  views: number;
  downloads: number;
}

export interface AlternativeSlugs {
  en: string;
  es: string;
  ja: string;
  fr: string;
  it: string;
  ko: string;
  de: string;
  pt: string;
}

export enum AssetType {
  Photo = 'photo',
}

export interface Exif {
  make: null | string;
  model: null | string;
  name: null | string;
  exposure_time: null | string;
  aperture: null | string;
  focal_length: null | string;
  iso: number | null;
}

export interface RandomResultLinks {
  self: string;
  html: string;
  download: string;
  download_location: string;
}

export interface Location {
  name: null | string;
  city: null | string;
  country: null | string;
  position: Position;
}

export interface Position {
  latitude: number;
  longitude: number;
}

export interface TopicSubmissions {
  archival?: Archival;
  wallpapers?: CoolTones;
  nature?: CoolTones;
  'cool-tones'?: CoolTones;
  travel?: CoolTones;
  'street-photography'?: Archival;
  'earth-hour'?: Archival;
}

export interface Archival {
  status: string;
  approved_on: string;
}

export interface CoolTones {
  status: string;
}

export interface Urls {
  raw: string;
  full: string;
  regular: string;
  small: string;
  thumb: string;
  small_s3: string;
}

export interface User {
  id: string;
  updated_at: string;
  username: string;
  name: string;
  first_name: string;
  last_name: string;
  twitter_username: null | string;
  portfolio_url: null | string;
  bio: null | string;
  location: null | string;
  links: UserLinks;
  profile_image: ProfileImage;
  instagram_username: null | string;
  total_collections: number;
  total_likes: number;
  total_photos: number;
  total_promoted_photos: number;
  accepted_tos: boolean;
  for_hire: boolean;
  social: Social;
}

export interface UserLinks {
  self: string;
  html: string;
  photos: string;
  likes: string;
  portfolio: string;
  following: string;
  followers: string;
}

export interface ProfileImage {
  small: string;
  medium: string;
  large: string;
}

export interface Social {
  instagram_username: null | string;
  portfolio_url: null | string;
  twitter_username: null | string;
  paypal_email: null;
}
